$kind: http-example
request:
  url: "{{baseUrl}}/inventory/:productId"
  method: PATCH
  headers:
    - key: Content-Type
      value: application/json
    - key: Accept
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  pathVariables:
    productId: "9681"
  body:
    type: json
    content: |-
      {
        "physical_qty": 150
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "message": "Invalid email or password."
      }
    $type: |-
      {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Invalid email or password."
          }
        }
      }
order: 2000
